[package]
name = "vulkan-renderer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version = "0.37.0+1.3.209"}
winit ="0.27.2"
glam = "0.21.3"